hash-format = "sha256"

[[files]]
file = "config/appleskin-client.toml"
hash = "e6609ffbea927ee6390b1317bb6f3abb3f31ee591ca5c1d5e748f5e625fefea1"

[[files]]
file = "config/armourers_workshop-client.toml"
hash = "9e08645e29feaaee9a5a318c5f2c1f37c2e7d380639a646afac183b7abe95b3f"

[[files]]
file = "config/armourers_workshop-common.toml"
hash = "962904bef159e9000d67eb687cdd4029631af2cbffbd47a7bf7c3e3185d20c37"

[[files]]
file = "config/canary.properties"
hash = "a37eb7f218ab61f3277a103a85c5bd14ff0abe0dff94e17883bcbb5ea28a3855"

[[files]]
file = "config/collective.json5"
hash = "600046b205e20aa3a2ff5af8a66a202c00a97b1c27a6c0675211dbe11d4c0b5f"

[[files]]
file = "config/comforts-server.toml"
hash = "e0ef27aa238d56b96c1a1c76f91cbc61a1ac91aa4dfc897101389f3ce6dad7a0"

[[files]]
file = "config/cosmeticarmorreworked-client.toml"
hash = "1f09257bc11babe19b5e78bce02ed7dcade4efab2a9353008bacb96ddd6bd75f"

[[files]]
file = "config/cosmeticarmorreworked-common.toml"
hash = "ad632cac4e88a5138ae60ff7304bb3586eb93e9d3b34f241e5d532c1e5d19e7e"

[[files]]
file = "config/create-client.toml"
hash = "eaa6a70baee42d0c714595f52d3c2a1800cdf53c875f8676235e2f180693ffe0"

[[files]]
file = "config/create-common.toml"
hash = "b2a49a7bbb48c346464a3bb17b72ebfa9eca06410f04bc0f518b5e049ab155fc"

[[files]]
file = "config/createaddition-common.toml"
hash = "32aca0fd9e162e0982bc903e1b2b29e8473c0ce644423ad767689af604a7b45c"

[[files]]
file = "config/curios-client.toml"
hash = "9c0985b85e67e704a3640d028186dc0b220fa69404b9555244add55eaf5d4794"

[[files]]
file = "config/dbe_v5_common.json"
hash = "eccd0c1b98be399a5ccae476814e18974844bff217c8f46468501c761042817c"

[[files]]
file = "config/decorative_blocks-common.toml"
hash = "45935895d117bb33a0495c5c2c129a3c8c8d328b3c225fb808ba48a0b57c7108"

[[files]]
file = "config/enchdesc.json"
hash = "31c1f5099f0deb10946338897737b96384d681034367adef94bb380211fe91f3"

[[files]]
file = "config/farmersdelight-client.toml"
hash = "e5f8f5743c23e6c1e569070d720f91e66495e8da03550a0d37d9a07c6d543014"

[[files]]
file = "config/farmersdelight-common.toml"
hash = "bb025f3ba2615e9a50d885c3e220fdb4bf98141c7e4b1680c717e51fcf392789"

[[files]]
file = "config/farmersrespite-common.toml"
hash = "1f11494139995bcd3782d3b01732d7f5ffc412e556c10ac49c2d79122f00503b"

[[files]]
file = "config/flywheel-client.toml"
hash = "0d0e22785b8811b4010b7cf39f78fcfb25e31e70558176a52cb9e95ea9202c8f"

[[files]]
file = "config/fml.toml"
hash = "eb5434c7520284945763f461841e91da86895a70324e13218a07824f81e5ec87"

[[files]]
file = "config/forge-client.toml"
hash = "534d9fc367bb58ded17ad2820df913dee00eb6e64ef9270c3a8e491db585f548"

[[files]]
file = "config/forge-common.toml"
hash = "a440d2a7ce939ef3c462475555a9a188263aebdbf13db600de3f01d9d312970c"

[[files]]
file = "config/forge-resource-caching.toml"
hash = "acfdb749a28106463b96980100a7e542b0b2bc3f9c9464196e0765a4f1c39061"

[[files]]
file = "config/framedblocks-client.toml"
hash = "84bd8537e2d4a8b53734671b8596ef0b3ca029f74179a1e364fc6627ed60c535"

[[files]]
file = "config/framedblocks-common.toml"
hash = "3df7937868159c8c2570d09c9ef9e0a1127dfbab70c3404c8fd069c7390d39ff"

[[files]]
file = "config/handoveryouritems.json5"
hash = "793dd29112341a3751e7d42bc8c2329fdd4971e271e0d58d4a3952250849bd68"

[[files]]
file = "config/immersive_weathering-client.toml"
hash = "248742388f422b61dfd82ab6a1c632bb4e12bf0a18c5413cbcee816b8192d051"

[[files]]
file = "config/immersive_weathering-common.toml"
hash = "e08f64b407cba59675682c56fef9fe5e6673b33fe19a1f88446215b9481a4b35"

[[files]]
file = "config/inventorio.json"
hash = "28089e4a0774909ab5353f49d38c820cfa35b54438a52117030f2790cd5e83d7"

[[files]]
file = "config/inventorio_shared.json"
hash = "e35014bddfc845a2bb07373a8f0df0663fa08ffec5cf080b479685327572d5f6"

[[files]]
file = "config/itshallnottick-common.toml"
hash = "e6073d21f51d475e3a192fb17d0fc9f7eaf3dffaae7a5bcf5aa1f76c1af8d334"

[[files]]
file = "config/jade/hide-entities.json"
hash = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"

[[files]]
file = "config/jade/jade.json"
hash = "8a59a7151051d7b45f134fd4b1a9f10bc7957cd90c09cd126b4f70a83e5cc994"

[[files]]
file = "config/jade/plugins.json"
hash = "13d53616a9fde0958b988960c2222c7ceca6e67c421c80c9d9d35487de23e10b"

[[files]]
file = "config/jade/sort-order.json"
hash = "d622807d6d3ed7a147e62289ba4dd40bc459b4e833603af4cb0e6157b0b05213"

[[files]]
file = "config/jei/blacklist.cfg"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/jei/jei-client.ini"
hash = "c513c22b5acbf79ca29858ba472bba4a6f969df405c61b37b7ee6554358d88ea"

[[files]]
file = "config/jei/jei-colors.ini"
hash = "c6328dcf3fb8b20a9f6ea6b61266ce289565c167353e183a105fb4915c36c072"

[[files]]
file = "config/jei/jei-debug.ini"
hash = "24f1a0313b8ae9b6bf450d962640312613fd0f9e9a21a26756b85a6b5ee3d46d"

[[files]]
file = "config/jei/jei-mod-id-format.ini"
hash = "34eb990ae2cf62220a0d1be95629bcac46e6732f1cd6f7b6fdc54bcae02916e5"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"
hash = "1377a281654cf3db6f343be095c479512943ca9e26db609bd81125532cf78278"

[[files]]
file = "config/naturescompass-client.toml"
hash = "4215398614d28a24d2fe39593bf25981dd67ae46f85bc710ee07ba2d37c74c0b"

[[files]]
file = "config/naturescompass-common.toml"
hash = "eebe4b4c01047b3d8cbf1106fcfe8af8e912ca62dfbb5258f46b36623b535fa2"

[[files]]
file = "config/polymorph-integrations.toml"
hash = "43a7425a314be7d78c2e31d44ab8f46c5ee824ab10906ab8909923d23646b6ad"

[[files]]
file = "config/quark-common.toml"
hash = "6df094c207f3a418ddca2d63183a7d550cfcdcfb19df454821ca5623a3efb0f3"

[[files]]
file = "config/railways-client.toml"
hash = "3c6b7c5a57e8fd090285b4be2aa4b0ae2cb91a028ce1ae199d88c0c99859c62f"

[[files]]
file = "config/railways-common.toml"
hash = "68cc9f605983fa6baff04f8fc98c1cdc8a6fa704700d49e4842631accf3bdfa9"

[[files]]
file = "config/snowyspirit-common.toml"
hash = "560ab7dabd920ad9f97762ac2c9ad9777323ac3660d9d057c6f40e077131f6e4"

[[files]]
file = "config/sophisticatedbackpacks-common.toml"
hash = "5ddb3891d55c31f63405d05410bb29928643874e7456c8e9cfd150a90a821e2c"

[[files]]
file = "config/sophisticatedcore-client.toml"
hash = "48e045efb78607ff217eb278f817f1036039d99e38715ef9a9c6e1f5bafbc24c"

[[files]]
file = "config/sophisticatedcore-common.toml"
hash = "c4a95a1a2ae78c9592aba513766565420d3342ca65d0c6a1b127b91960caae57"

[[files]]
file = "config/supplementaries-client.toml"
hash = "1ac07c61a61acf7ed86b3257aacb3c839f6b88cb0653e01560ac723289303a54"

[[files]]
file = "config/supplementaries-common.toml"
hash = "98f1fb6ad369dbee74997bd325d2b3358eb5c21c715b6139d43f04d42238499c"

[[files]]
file = "config/tis3d-client.toml"
hash = "9cfc4c5ae34f0babd567e4af5a046a4c50144eebeaef7ee8103842188c1f92b0"

[[files]]
file = "config/tis3d-common.toml"
hash = "0c8dd966db53f34bf9f2968a0b58a53b2be55492ec40daf04999bfec66a4ca48"

[[files]]
file = "journeymap/config/5.9/journeymap.core.config"
hash = "7973837c42be9904578fd5be91d7c9797345ca4c1d3be3a6fe7d2203f93f7e31"

[[files]]
file = "journeymap/config/5.9/journeymap.fullmap.config"
hash = "2d1d2985426091c7417c00957bf4eb9ccffa4d4b3f1a3767a0e1df47bd843743"

[[files]]
file = "journeymap/config/5.9/journeymap.minimap.config"
hash = "12178d2797b442ffcd11dc4225fc7119f335aa8d6b5f4c9c18010920aa779455"

[[files]]
file = "journeymap/config/5.9/journeymap.minimap2.config"
hash = "a2dda841dbb5c0b1aa3e05917ba6e59c194e6af515434fe0394099a785062f15"

[[files]]
file = "journeymap/config/5.9/journeymap.topo.config"
hash = "7f713335de7a597c930ffb02279bce528b8884e9b563474c4204032314c2a852"

[[files]]
file = "journeymap/config/5.9/journeymap.waypoint.config"
hash = "8d17e32f25c25433b6d70bcc2140e91619097b8d3211acdd9f7d83f036a5adc3"

[[files]]
file = "journeymap/config/5.9/journeymap.webmap.config"
hash = "f13dddab5b166d39bf307229681addf772d22cd48ec289911f7c1a4a94b94ec9"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/biome/-4,0.png"
hash = "bab2af239e24632fbcefb782e6b3ae7d4955e7993216a64ea7442204129c4a9d"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/cache/r.-4.0.mca"
hash = "a9c622d54bbec16d87b687f1e2008399128ed0cba2a70c7cf786d73443e71f69"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/day/-4,0.png"
hash = "6e173f406c658806bce9ae31c8fe1d0f5866a0ceaa8ddd7984c559406bd3ec54"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/night/-4,0.png"
hash = "3ab87cc67e2f6976afbc405ecc9b38321ad86bc55b8628ec6249cf9b07fe3929"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/topo/-4,0.png"
hash = "4f51fa3c84b562d296a795fad46b8912259d87bcd0b99d88894f7edbfb6026c3"

[[files]]
file = "journeymap/data/mp/Minecraft~Server_fa8c4c3f~d505~4200~833e~4badb4e60751/overworld/topo/cache/r.-4.0.mca"
hash = "a99e408e75c5de507b911b50b03d5ba1e4e97426ccd7db4e5013c474e0a9180c"

[[files]]
file = "journeymap/icon/theme/default.theme.config"
hash = "21af30bf8e646b63fdc52a25e1dc0eb20ffa0085d688767e424333d767be8629"

[[files]]
file = "journeymap/icon/theme/flat/DesertTemple.theme2.json"
hash = "3fbea9b4f7a132c50c2225f66e31bcc0421abee5ebf4d0faa2ce70055921ccd2"

[[files]]
file = "journeymap/icon/theme/flat/EndCity.theme2.json"
hash = "aa20458b3eb842261db12d9ce79509284049021bf8d9624ed1b17e6a43e891cf"

[[files]]
file = "journeymap/icon/theme/flat/ForestMansion.theme2.json"
hash = "8c3305e78ac46c4b8a7b84ab4e0707ff4ed9b8011c3e34c153c7ba175864887e"

[[files]]
file = "journeymap/icon/theme/flat/NetherFortress.theme2.json"
hash = "ca6f39a57b624ac3a02500a1bcc7671b8d09d0e350b44dde5141f3a1ea833a77"

[[files]]
file = "journeymap/icon/theme/flat/OceanMonument.theme2.json"
hash = "174ac660305e06603087f3caa2fd64e3c7bd486a02a5a07723e88c63cf271475"

[[files]]
file = "journeymap/icon/theme/flat/Purist.theme2.json"
hash = "d32aa0552005de366508699916035f5cc3a8e126114adf064d3cfd0086f9cad2"

[[files]]
file = "journeymap/icon/theme/flat/Stronghold.theme2.json"
hash = "70ac933ca3a16895c3826edfac645e6eec2f2b3de07dd86da7c7005157e4b824"

[[files]]
file = "journeymap/journeymap.log"
hash = "33539b7cd7aa2674bad103ca881fd20efd258de37564e725019f9da8ce015e94"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1be3c626f8c8e445e57444f2559dc590edafc75b6c8c18d4599703dbc614a7e8"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "9332d7895d9a9d8827aa4de02b1c96884fec9402cc66bd90e64f64bfc0c5f814"
metafile = true

[[files]]
file = "mods/armourers-workshop.pw.toml"
hash = "98052566db2523510e09459d3f22c0a1544ee6c13f0c10d1aab7849c8ed1b383"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "93e1dd0ac54ad216cf4ee82e5ab12a7de23d7cdfe7a27eb0b0c168a1c939db4a"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "e7a31bca2c89624f212365c8ba63364652ae7163af1b0d6effafb4f1b27c2d42"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "ed3a185fba569969c28c02ff44d0e5266d297d1345498dfdce3c771439ddc8b8"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d3772ba304230f9b7f1c62ea44e1b65dd08927f1fa1170817d2665baa8c9951b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "5880c81df1af395ec3762eff4e98c78f7b75e62db67e1d191a1772d79aabc073"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "187939745940bb83187c6cacaabbae764ea12eee18037fb3f7f3255214a0035f"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "ed7d38776b40ced95d806d0debaa6faa5b999d1c46095d3587d6a9ff3947c0cc"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "a94bec93c6e2f350d4bfd94d6f557fca51ef4358aa4a714e87816243537a6623"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "c98b92c96eb546872a0d203969ddba29a17f6ab0e57ff93081d81a138562e8b7"
metafile = true

[[files]]
file = "mods/create-alloyed.pw.toml"
hash = "710fba5cc4183a0d1661132614e5acd08ee3c8105dea4695b640fafe6a6b14c0"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "bc0e7891bfb4937b5cfd836d3fe49b686b85971c22134a7eace351f3aac71ed6"
metafile = true

[[files]]
file = "mods/create-confectionery.pw.toml"
hash = "31ccc987a5d973083662a881aa0c35a0f5ae66cc01ee0bb612b23f9bfe4e37a6"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "21a49f8463e44ba3325eabce071478a365cd102a601e9ed837e2f25a52670a6c"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "1a8e4dffd75706c6c0089f9649aa1f215dba82049b4f39c25168a2d7d2474e88"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "34e59e9e7de40c0c50c1739975a76e6bdc354eab9645e25d36225901739a0cbd"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "3263538e83dbfcdfccbe8b278cf163894a992672f97db3efb551c7a47cdf8ff3"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "53e0dbe77a570509bcfcf80b29f89baa9b80537e70ade7aa93ca676545598b9b"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "823537b84dc4c55889d23255e42248e6eeb02fad57c46aa694b6ce26451a4a86"
metafile = true

[[files]]
file = "mods/daves-building-extended.pw.toml"
hash = "92f6465f902ed9dd3fe975e261472224e4d9aa71e08af443e596ca87e5d83dde"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "b33441b07f85bd9d3a7757020afcc01b80a44cc376b29475ed246b0f97ec7d11"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "32919ba2d15d55cec37bc8759064e1983e9a917c3ccfe25c4ad880cbf0a7026b"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "03c419552b4da26729b658e78546ed045e5d9b25bca5f9253ebfb6a33cd91d1f"
metafile = true

[[files]]
file = "mods/farmers-respite.pw.toml"
hash = "51436656f2fbac1996b8b0db1313674727e70dd14ed8e102a4ea8905c82b4860"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "da09edd338fa641d7eee1b96ecc2cc5e6dc9d299c68da33741b3b81854a551ef"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
hash = "3e9b9722da123b1d4120f0d9aba8de9968aba4aad6e9c7564423672171e00d9e"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "68ffae45121468e8205b8be4d2d67b723928de3ffb1aeda068eea3d6c9d246e0"
metafile = true

[[files]]
file = "mods/hand-over-your-items.pw.toml"
hash = "9ebe517ed79c7e7e8d65c4a9386d0e814491c9cb614501fcc6a25d8c80c73593"
metafile = true

[[files]]
file = "mods/immersive-weathering-forge.pw.toml"
hash = "00f3dc4debce9b682bf3a785418f977639e692fe2848dcc0634663b6512a31a6"
metafile = true

[[files]]
file = "mods/inventorio-forge.pw.toml"
hash = "4a62e1b9a7f3c2b858b014e14a3bd1b79d637f41ee42a6e541304053fc4b27c3"
metafile = true

[[files]]
file = "mods/it-shall-not-tick.pw.toml"
hash = "2baf89f01663c240143e8c7aa9e5813f82dabbd84f38832609707d43f9e2f2a3"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "4b71171ba73da26c1582f013ebd49882b7d101da463a71ada07854c1aede2206"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "42a7d4840c97d0c5edbeace9ae52190b1cbdfb583be783ea4e0aa6e0b28ef6b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f2526b02e5bf3c45d1c34452d8e77c210a57a8eedd3a13bf5031c97b247a3e59"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "95a56fc61a70712af47b0b0e3c07ef94a3aa3b7e8bc76c0c6631796eac39f511"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "c097a4165a61f279c1ccc200356869896b665c27023e8fe5008e29018ceb0ff0"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "85e9b8f568b9db744ffabf4d9e31ba4e1f57d7fdf4a1fd5f90a8e7cb24033611"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
hash = "409d32841ac9cfda6ff7d5d78eb2717f3ddf789f3773cab39b056574c2e3ec31"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "63800317329d340d3550b00dda4fecb2861cc6a643c2390d34f446c550ff9f06"
metafile = true

[[files]]
file = "mods/nethers-delight.pw.toml"
hash = "f349720f05bacd441290629a2aabb95a8c5f742227037900db022f4e0258f2de"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "dfb6c4735efa3dacda748935cc498b9462bd5c6d21d349a1da5c8fd82208c7ae"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "58e06eeb61c9640f48bca3a95ca50af757792719146a33a7a1a31025e875858a"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "5617cd09c1156295c3dcb279c1f68db0edad1e6233906f54f845480f748376fe"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "a0b717e012441e2bef8d9c1b7222dd9b25adf06d55ace1144eabf3ee6f637733"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "87a9981fb934fde9aaf6db02ba3513955bd359aab6c4f4f8427e8b6bd8e30602"
metafile = true

[[files]]
file = "mods/radon.pw.toml"
hash = "981be0bc0eaa7492cfbe2068ecdb12424ecfba11166b1a264d7928c6391d7271"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
hash = "d6a02b617d73812b20a2f8e483ea9791ecbf8de2649611bde123b6bb5d9ce365"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "4932c23c8228894af61844bab27073f9d189a061459ccc4f14c8dbd94c0e238c"
metafile = true

[[files]]
file = "mods/snowy-spirit.pw.toml"
hash = "5be509df9294d557b240b4957426b54ff2ec79b6cc356e4c0d94a10a02e2a9c1"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "6a37f93609d5dc95808f5bc477a6be4e6b3623b9a438b1a275e436ab1f7fb63f"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "17a2b4189e483db332f550a133a153aa841d666ab7cf2923ae5573f60d25979f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "91fef1da41212259927b6c8df2a2e8e35a81488fc23658feed0d3b9730175e4f"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "5ee2c0d175a1018ca40e6ded917f9db40dadc120888388612bee5d6eb2ac26c5"
metafile = true

[[files]]
file = "mods/tis-3d.pw.toml"
hash = "c889fbe21dd6c94f2de4ec3de1c3de45be0f4e076ea5e597424094cdd7343a5a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "719da66ac6adbf00ace4a021f1bfcd6aca271b16caa40629de9e73a79b844905"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "28abbc86e422d9f8263dd45132bdab8fa8ce4e2f9cb415997f821e0ab0e02235"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "3d0e7fcc4b54e29b4ee0a73d0114a23505560a2779b7e25c34a26da62b203498"
metafile = true

[[files]]
file = "options.txt"
hash = "cfd56896a35465291a2d383392313535530391a8de08ec9f42c8bc7dc6a231ce"

[[files]]
file = "servers.dat"
hash = "14343afaf87c0dd376a5ff526e01222e734118e856bf8c059df713e3882b5339"

[[files]]
file = "servers.dat_old"
hash = "14343afaf87c0dd376a5ff526e01222e734118e856bf8c059df713e3882b5339"
